export const rwandaProvinces = [
  {
    name: "Kigali City",
    districts: [
      {
        name: "Gasabo",
        sectors: [
          "Bumbogo",
          "Gatsata",
          "Jali",
          "Gikomero",
          "Gisozi",
          "Jabana",
          "Kinyinya",
          "Ndera",
          "Nduba",
          "Remera",
          "Rusororo",
          "Rutunga",
          "Kacyiru",
          "Kimihurura",
          "Kimironko",
          "Giticyinyoni",
        ],
      },
      {
        name: "Kicukiro",
        sectors: [
          "Gahanga",
          "Gatenga",
          "Gikondo",
          "Kagarama",
          "Kanombe",
          "Kicukiro",
          "Kigarama",
          "Masaka",
          "Niboye",
          "Nyarugunga",
        ],
      },
      {
        name: "Nyarugenge",
        sectors: [
          "Gitega",
          "Kanyinya",
          "Kigali",
          "Kimisagara",
          "Mageragere",
          "Muhima",
          "Nyakabanda",
          "Nyamirambo",
          "Nyarugenge",
          "Rwezamenyo",
        ],
      },
    ],
  },
  {
    name: "Eastern Province",
    districts: [
      {
        name: "Bugesera",
        sectors: [
          "Gashora",
          "Juru",
          "Kamabuye",
          "Mareba",
          "Mayange",
          "Musenyi",
          "Mwogo",
          "Ngeruka",
          "Ntarama",
          "Nyamata",
          "Nyarugenge",
          "Rilima",
          "Ruhuha",
          "Rweru",
          "Shyara",
        ],
      },
      {
        name: "Gatsibo",
        sectors: [
          "Gasange",
          "Gatsibo",
          "Gitoki",
          "Kabarore",
          "Kageyo",
          "Kiramuruzi",
          "Kiziguro",
          "Muhura",
          "Murambi",
          "Ngarama",
          "Nyagihanga",
          "Remera",
          "Rugarama",
          "Rwimbogo",
        ],
      },
      {
        name: "Kayonza",
        sectors: [
          "Gahini",
          "Kabare",
          "Kabarondo",
          "Mukarange",
          "Murama",
          "Murundi",
          "Mwiri",
          "Ndego",
          "Nyamirama",
          "Rukara",
          "Ruramira",
          "Rwinkwavu",
        ],
      },
      {
        name: "Kirehe",
        sectors: [
          "Gahara",
          "Gatore",
          "Kigarama",
          "Kigina",
          "Kirehe",
          "Mahama",
          "Mpanga",
          "Musaza",
          "Mushikiri",
          "Nasho",
          "Nyamugari",
          "Nyarubuye",
        ],
      },
      {
        name: "Ngoma",
        sectors: [
          "Gashanda",
          "Jarama",
          "Karembo",
          "Kazo",
          "Kibungo",
          "Mugesera",
          "Murama",
          "Mutenderi",
          "Remera",
          "Rukira",
          "Rukumberi",
          "Rurenge",
          "Sake",
          "Zaza",
        ],
      },
      {
        name: "Nyagatare",
        sectors: [
          "Gatunda",
          "Karama",
          "Karangazi",
          "Katabagemu",
          "Kiyombe",
          "Matimba",
          "Mimuli",
          "Mukama",
          "Musheri",
          "Nyagatare",
          "Rukomo",
          "Rwempasha",
          "Rwimiyaga",
          "Tabagwe",
        ],
      },
      {
        name: "Rwamagana",
        sectors: [
          "Fumbwe",
          "Gahengeri",
          "Gishari",
          "Karenge",
          "Kigabiro",
          "Muhazi",
          "Munyaga",
          "Munyiginya",
          "Musha",
          "Muyumbu",
          "Mwulire",
          "Nyakariro",
          "Nzige",
          "Rubona",
        ],
      },
    ],
  },
  {
    name: "Northern Province",
    districts: [
      {
        name: "Burera",
        sectors: [
          "Bungwe",
          "Butaro",
          "Cyanika",
          "Cyeru",
          "Gahunga",
          "Gatebe",
          "Gitovu",
          "Kagogo",
          "Kinoni",
          "Kinyababa",
          "Kivuye",
          "Nemba",
          "Rugarama",
          "Rugengabari",
          "Ruhunde",
          "Rusarabuye",
          "Rwerere",
        ],
      },
      {
        name: "Gicumbi",
        sectors: [
          "Bukure",
          "Bwisige",
          "Byumba",
          "Cyumba",
          "Giti",
          "Kaniga",
          "Manyagiro",
          "Miyove",
          "Mukarange",
          "Muko",
          "Mutete",
          "Nyamiyaga",
          "Nyankenke",
          "Rubaya",
          "Rukomo",
          "Rushaki",
          "Rutare",
          "Ruvune",
          "Rwamiko",
          "Shangasha",
        ],
      },
      {
        name: "Musanze",
        sectors: [
          "Busogo",
          "Cyuve",
          "Gacaca",
          "Gashaki",
          "Gataraga",
          "Kimonyi",
          "Kinigi",
          "Muhoza",
          "Muko",
          "Musanze",
          "Nkotsi",
          "Nyange",
          "Remera",
          "Rwaza",
          "Shingiro",
        ],
      },
      {
        name: "Rulindo",
        sectors: [
          "Base",
          "Burega",
          "Bushoki",
          "Buyoga",
          "Cyinzuzi",
          "Cyungo",
          "Kinihira",
          "Kisaro",
          "Masoro",
          "Mbogo",
          "Murambi",
          "Ngoma",
          "Ntarabana",
          "Rukozo",
          "Rusiga",
          "Shyorongi",
          "Tumba",
        ],
      },
      {
        name: "Gakenke",
        sectors: [
          "Busengo",
          "Coko",
          "Cyabingo",
          "Gakenke",
          "Gashenyi",
          "Mugunga",
          "Janja",
          "Kamubuga",
          "Karambo",
          "Kivuruga",
          "Mataba",
          "Minazi",
          "Muhondo",
          "Muyongwe",
          "Muzo",
          "Nemba",
          "Ruli",
          "Rusasa",
          "Rushashi",
        ],
      },
    ],
  },
  {
    name: "Southern Province",
    districts: [
      {
        name: "Gisagara",
        sectors: [
          "Gikonko",
          "Gishubi",
          "Kansi",
          "Kibilizi",
          "Kigembe",
          "Mamba",
          "Muganza",
          "Mugombwa",
          "Mukindo",
          "Musha",
          "Ndora",
          "Nyanza",
          "Save",
        ],
      },
      {
        name: "Huye",
        sectors: [
          "Gishamvu",
          "Karama",
          "Kigoma",
          "Kinazi",
          "Maraba",
          "Mbazi",
          "Mukura",
          "Ngoma",
          "Ruhashya",
          "Rusatira",
          "Rwaniro",
          "Simbi",
          "Tumba",
          "Huye",
        ],
      },
      {
        name: "Kamonyi",
        sectors: [
          "Gacurabwenge",
          "Karama",
          "Kayenzi",
          "Kayumbu",
          "Mugina",
          "Musambira",
          "Ngamba",
          "Nyamiyaga",
          "Nyarubaka",
          "Rukoma",
          "Rugarika",
          "Runda",
        ],
      },
      {
        name: "Muhanga",
        sectors: [
          "Cyeza",
          "Kabacuzi",
          "Kibangu",
          "Kiyumba",
          "Muhanga",
          "Mushishiro",
          "Nyabinoni",
          "Nyamabuye",
          "Nyarusange",
          "Rongi",
          "Rugendabari",
          "Shyogwe",
        ],
      },
      {
        name: "Nyamagabe",
        sectors: [
          "Buruhukiro",
          "Cyanika",
          "Gasaka",
          "Gatare",
          "Kaduha",
          "Kamegeri",
          "Kibirizi",
          "Kibumbwe",
          "Kitabi",
          "Mbazi",
          "Mugano",
          "Musange",
          "Musebeya",
          "Mushubi",
          "Nkomane",
          "Tare",
          "Uwinkingi",
        ],
      },
      {
        name: "Nyanza",
        sectors: [
          "Busasamana",
          "Busoro",
          "Cyabakamyi",
          "Kibirizi",
          "Mukingo",
          "Muyira",
          "Ntyazo",
          "Nyagisozi",
          "Rwabicuma",
        ],
      },
      {
        name: "Nyaruguru",
        sectors: [
          "Busanze",
          "Cyahinda",
          "Kibeho",
          "Kivu",
          "Mata",
          "Muganza",
          "Munini",
          "Ngera",
          "Ngoma",
          "Nyabimata",
          "Nyagisozi",
          "Ruheru",
          "Ruramba",
          "Rusenge",
        ],
      },
      {
        name: "Ruhango",
        sectors: ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Kinihira", "Mbuye", "Mwendo", "Ntongwe", "Ruhango"],
      },
    ],
  },
  {
    name: "Western Province",
    districts: [
      {
        name: "Karongi",
        sectors: [
          "Bwishyura",
          "Gashari",
          "Gishyita",
          "Gisovu",
          "Gitesi",
          "Mubuga",
          "Murambi",
          "Murundi",
          "Mutuntu",
          "Rubengera",
          "Rugabano",
          "Ruganda",
          "Rwankuba",
        ],
      },
      {
        name: "Ngororero",
        sectors: [
          "Bwira",
          "Gatumba",
          "Hindiro",
          "Kabaya",
          "Kageyo",
          "Kavumu",
          "Matyazo",
          "Muhanda",
          "Muhororo",
          "Ndaro",
          "Ngororero",
          "Nyange",
          "Sovu",
        ],
      },
      {
        name: "Nyabihu",
        sectors: [
          "Bigogwe",
          "Jenda",
          "Jomba",
          "Kabatwa",
          "Karago",
          "Kintobo",
          "Mukamira",
          "Muringa",
          "Rambura",
          "Rugera",
          "Rurembo",
          "Shyira",
        ],
      },
      {
        name: "Nyamasheke",
        sectors: [
          "Bushekeri",
          "Bushenge",
          "Cyato",
          "Gihombo",
          "Kagano",
          "Kanjongo",
          "Karambi",
          "Karengera",
          "Kirimbi",
          "Macuba",
          "Mahembe",
          "Nyabitekeri",
          "Rangiro",
          "Ruharambuga",
          "Shangi",
        ],
      },
      {
        name: "Rubavu",
        sectors: [
          "Bugeshi",
          "Busasamana",
          "Cyanzarwe",
          "Gisenyi",
          "Kanama",
          "Kanzenze",
          "Mudende",
          "Nyakiliba",
          "Nyamyumba",
          "Nyundo",
          "Rubavu",
          "Rugerero",
        ],
      },
      {
        name: "Rusizi",
        sectors: [
          "Bugarama",
          "Butare",
          "Bweyeye",
          "Gashonga",
          "Giheke",
          "Gihundwe",
          "Gitambi",
          "Kamembe",
          "Muganza",
          "Mururu",
          "Nkanka",
          "Nkombo",
          "Nkungu",
          "Nyakabuye",
          "Nyakarenzo",
          "Nzahaha",
          "Rwimbogo",
        ],
      },
      {
        name: "Rutsiro",
        sectors: [
          "Boneza",
          "Gihango",
          "Kigeyo",
          "Kivumu",
          "Manihira",
          "Mukura",
          "Murunda",
          "Musasa",
          "Mushonyi",
          "Mushubati",
          "Nyabirasi",
          "Ruhango",
          "Rusebeya",
        ],
      },
    ],
  },
]
